use lxm6009;
CREATE TABLE WORLD_CUPS (
  YEAR                INT,
  COUNTRY            VARCHAR(50),
  WINNER             VARCHAR(50),
  RUNNERS_UP          VARCHAR(50),
  THIRD               VARCHAR(50),
  FOURTH              VARCHAR(50),
  GOALSSCORED         INT,
  QUALIFIEDTEAMS      INT,
  MATCHESPLAYED       INT,
  ATTENDANCE          VARCHAR(255),
  CONSTRAINT pk_world_cups PRIMARY KEY (YEAR)
);



CREATE TABLE WORLD_CUP_MATCHES (
  YEAR                INT(4) REFERENCES WORLD_CUPS(YEAR) ON DELETE CASCADE,
  DATETIME            VARCHAR(50),
  STAGE               VARCHAR(50),
  STADIUM            VARCHAR(50),
  CITY               VARCHAR(50),
  HOMETEAMNAME      VARCHAR(50),
  HOMETEAMGOALS     INT(5),
  AWAYTEAMGOALS     INT(5),
  AWAYTEAMNAME      VARCHAR(50),
  WINCONDITIONS     VARCHAR(50),
  ATTENDANCE        VARCHAR(50),
  HALF_TIMEHOMEGOALS INT(5),
  HALF_TIMEAWAYGOALS INT(5),
  REFEREE             VARCHAR(50),
  ASSISTANT1          VARCHAR(50),
  ASSISTANT2          VARCHAR(50),
  ROUNDID            INT(5) REFERENCES WORLD_CUP_PLAYERS(ROUND_ID) ON DELETE CASCADE,
  MATCHID            INT(5),
  HOMETEAMINITIALS  VARCHAR(50),
  AWAYTEAMINITIALS  VARCHAR(50),
  CONSTRAINT pk_world_cups_matches PRIMARY KEY (ROUNDID,MATCHID)
);

CREATE TABLE WORLD_CUP_PLAYERS (
  ROUNDID            INT(5) REFERENCES WORLD_CUP_MATCHES(ROUND_ID) ON DELETE CASCADE,
  MATCHID            INT(5) REFERENCES WORLD_CUP_MATCHES(MATCH_ID) ON DELETE CASCADE,
  TEAMINITIALS       VARCHAR(50),
  COACHNAME          VARCHAR(50),
  LINE_UP              VARCHAR(50),
  SHIRTNUMBER         INT(5),
  PLAYERNAME          VARCHAR(50),
  POSITION            VARCHAR(50),
  EVENT              VARCHAR(50)
);
ALTER TABLE WORLD_CUP_MATCHES
ADD CONSTRAINT fk_world_cup_matches_year
FOREIGN KEY (YEAR) REFERENCES WORLD_CUPS (YEAR);
CREATE INDEX idx_world_cup_matches_round_id ON WORLD_CUP_MATCHES (ROUNDID);
ALTER TABLE WORLD_CUP_PLAYERS
ADD CONSTRAINT fk_world_cup_players_round_id
FOREIGN KEY (ROUNDID) REFERENCES WORLD_CUP_MATCHES (ROUNDID);
CREATE INDEX idx_world_cup_matches_matchid ON WORLD_CUP_MATCHES (MATCHID);
ALTER TABLE WORLD_CUP_PLAYERS
ADD CONSTRAINT fk_world_cup_players_matchid
FOREIGN KEY (MATCHCHID) REFERENCES WORLD_CUP_MATCHES (MATCHID);

